name: tlv4j-ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./tlv4j
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./tlv4j
    - name: Upload coverage report
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
      working-directory: ./tlv4j