name: tlv4j-ci
on: [push]
jobs:
  build:
    environment: DEFAULT
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./tlv4j
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./tlv4j
    # - name: Generate coverage report
    #   run: ./gradlew codeCoverageReport
    #   working-directory: ./promotion-notifier-backend
    # - name: Upload coverage report
    #   run: bash <(curl -s https://codecov.io/bash)
    #   working-directory: ./promotion-notifier-backend